module.exports = {
  title: 'Trivia Farm',
  description: 'Music Trivia Generated by Non-humans',
  keywords: ['trivia', 'music', 'opensource', 'hibing'],
  // your site url without trailing slash
  url: 'https://trivia.farm',
  // how many posts you want to show for each page
  paginate: 6
  // if you want to add disqus to your site
  // disqusShortname: "your-shortname"
};
